name: cache-test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: prime-cache-71c854a
        id: cache-step
        uses: actions/cache@v4
        with:
          key: cache-71c854a
          path: ~/.cache/pip

      - name: show-cache-result
        run: echo "Cache hit? ${{ steps.cache-step.outputs.cache-hit }}"

      - name: Install dependencies
        run: pip install -r requirements.txt
